server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/api_forum
    username: postgres
    password: 197197
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true